sudo: required
dist: trusty
env:
- linux
language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
branches:
  only:
  - master
git:
  depth: 1
script:
- sbt clean coverage test coverageReport
after_success:
- bash <(curl -s https://codecov.io/bash) -t ca2f63fc-acb1-4c45-9fb5-29f60e961155
notifications:
  slack:
    secure: aYgaH20Zq3CeCpoTHmHI1n5S3Fl4/UDP/lD+Q7e991KXxf6VrG0A/mqADN0mMvBJOpMyK4KyTH3W1T4iN/PlZnofGHn08/UNXWhIf4YlaBZiiOvep1o16LgMqvlzLwbhYpT/d8vBq56QBlv0WDi94u7umZveDFqt3AcedwhmbEYj232ERKIm1yvW6P+NhlEHStvQy+ceKVj4/go0qYI0nJ+eI5YYJZk5eF31mczHncgDrw9ixQ99Sh5MMm2nOX1N3wR4leduE7t9z+YxGhLDauddTRRvhO4RDDmp1P662efLF7fDID1tWNiqctIRQfxM67wowBVcdtOZ5uAYK1gFL9mEHke6MyqHVPQkh8W83VuFg5U8gloz1bfhXlrmTfZyRO8KO93TpzXOxr0jpBs5bgY1TdCSeKtLHTvYzeBQgYz6ypT13DRP2L2ZHvNioRer8P++vki+DW65WNdplGaBqcuriI0x3z8SY1jGdRN5RQhFcbgduJNaglvm9KsCBcJNs05QaMSpoiEOni+a1xzgtjI7BEPRVDtIChNR/bwmXwwy1jj5HsjvHi+iwK60pFiL80PsVneAycUTuf4PstmGzjnxPetPOYRzdeAmP/Y/AgxZpWuKAXtBlULuxVHXY2tthYbazo7qsKktK4mtTmhR5IejeNYKE0pT309cal4aW90=
